// Command docsgen writes docs/imapsync-options.md.
//
// Run it with `go generate ./...`. The file it writes is committed, and
// TestTheGeneratedOptionDocIsCurrent fails if it is stale, so the doc cannot
// drift away from the code that produces it.
//
// The two halves come from two places, and neither is written by hand:
//
//   - the imapsync support matrix, from internal/compat's option table, which
//     is the same table the shim executes;
//   - the native reference, from cobra's own help output, captured by running
//     the commands. The command tree lives in package main, which Go will not
//     let this program import, so it asks the binary instead of the package.
package main

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/hilli/imapsync-go/internal/compat"
)

// buildTimeout bounds the whole run. Every slow part of this program is a `go`
// subprocess, and one that never returns would hang a `go generate` with no
// indication of which command it was waiting for.
const buildTimeout = 10 * time.Minute

// nativeCommands are the command paths whose help is quoted in full.
var nativeCommands = [][]string{
	{},
	{"sync"},
	{"compat"},
	{"probe"},
	{"oauth"},
	{"oauth", "login"},
}

func main() {
	ctx, cancel := context.WithTimeout(context.Background(), buildTimeout)
	defer cancel()

	root, err := moduleRoot(ctx)
	if err != nil {
		fail(err)
	}

	var b strings.Builder
	writeHeader(&b)
	writeSupport(&b, compat.Options())
	if err := writeNative(ctx, &b, root); err != nil {
		fail(err)
	}

	out := filepath.Join(outputRoot(root), "docs", "imapsync-options.md")
	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil { //nolint:gosec // documentation
		fail(err)
	}
	fmt.Fprintf(os.Stderr, "wrote %s\n", out)
}

// outputRoot is the module root, unless DOCSGEN_OUT names somewhere else.
// The staleness test uses it to regenerate into a scratch directory, so a
// failing test reports the drift rather than quietly repairing it.
func outputRoot(root string) string {
	if dir := os.Getenv("DOCSGEN_OUT"); dir != "" {
		return dir
	}
	return root
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "docsgen:", err)
	os.Exit(1)
}

// moduleRoot finds the directory holding go.mod, so the generator works from
// wherever go generate happens to run it.
func moduleRoot(ctx context.Context) (string, error) {
	out, err := exec.CommandContext(ctx, "go", "env", "GOMOD").Output()
	if err != nil {
		return "", fmt.Errorf("locating the module: %w", err)
	}
	gomod := strings.TrimSpace(string(out))
	if gomod == "" || gomod == os.DevNull {
		return "", errNotInModule
	}
	return filepath.Dir(gomod), nil
}

var errNotInModule = fmt.Errorf("not inside a module")

func writeHeader(b *strings.Builder) {
	b.WriteString("# Options\n\n" +
		"<!-- Generated by internal/docsgen. Do not edit; run `go generate ./...`. -->\n\n" +
		"This has two halves.\n\n" +
		"**[imapsync options](#imapsync-options)** lists every option imapsync 2.x accepts\n" +
		"and what `imapsync-go compat` does with it. It is generated from the same table\n" +
		"the shim executes, so it describes what the tool does rather than what anyone\n" +
		"remembers it doing.\n\n" +
		"**[Native reference](#native-reference)** is the help for `imapsync-go`'s own\n" +
		"commands, which are what `imapsync-go sync` takes directly.\n\n")
}

func writeSupport(b *strings.Builder, opts []compat.Support) {
	counts := map[compat.Status]int{}
	for _, o := range opts {
		counts[o.Status]++
	}

	b.WriteString("## imapsync options\n\n")
	fmt.Fprintf(b, "%d options: %d translate to a native flag, %d build an endpoint URL, "+
		"%d are accepted and do nothing, and %d are refused.\n\n",
		len(opts),
		counts[compat.StatusTranslated],
		counts[compat.StatusEndpoint],
		counts[compat.StatusIgnored],
		counts[compat.StatusRefused])

	b.WriteString("A **refused** option stops the run rather than being quietly dropped: an\n" +
		"option that changes which messages move, or where they land, is not something to\n" +
		"guess about. An **ignored** one is accepted because it asks for what already\n" +
		"happens here.\n\n")

	for _, g := range groupsOf(opts) {
		fmt.Fprintf(b, "### %s\n\n", g.title)
		b.WriteString("| Option | Value | Notes |\n|---|---|---|\n")
		for _, o := range g.opts {
			writeRow(b, o)
		}
		b.WriteString("\n")
	}
}

type group struct {
	title string
	opts  []compat.Support
}

// groupsOf splits the table by what becomes of each option, which is the
// question a reader arrives with: they have a command line and want to know
// whether it will run.
func groupsOf(opts []compat.Support) []group {
	byStatus := map[compat.Status][]compat.Support{}
	for _, o := range opts {
		byStatus[o.Status] = append(byStatus[o.Status], o)
	}
	for _, list := range byStatus {
		sort.Slice(list, func(i, j int) bool { return list[i].Name < list[j].Name })
	}
	return []group{
		{"Translated to a native flag", byStatus[compat.StatusTranslated]},
		{"Folded into the endpoint URLs", byStatus[compat.StatusEndpoint]},
		{"Accepted, but they do nothing", byStatus[compat.StatusIgnored]},
		{"Refused", byStatus[compat.StatusRefused]},
	}
}

func writeRow(b *strings.Builder, o compat.Support) {
	name := "`--" + o.Name + "`"
	for _, a := range o.Aliases {
		name += "<br>`--" + a + "`"
	}

	var notes string
	switch o.Status {
	case compat.StatusTranslated:
		notes = "becomes `" + o.Native + "`"
	case compat.StatusEndpoint:
		notes = "builds `--source-url` or `--dest-url`"
	case compat.StatusIgnored, compat.StatusRefused:
		notes = o.Why
	}
	if o.Negates() {
		notes += "<br>`--no" + o.Name + "`: " + negatedNote(o)
	}

	value := string(o.Value)
	if value == "" {
		value = "—"
	}

	fmt.Fprintf(b, "| %s | %s | %s |\n", name, value, escapePipes(notes))
}

func negatedNote(o compat.Support) string {
	switch o.NegatedStatus {
	case compat.StatusTranslated:
		return "becomes `" + o.NegatedNative + "`"
	case compat.StatusEndpoint:
		return "builds the endpoint URL"
	default:
		return string(o.NegatedStatus) + ", " + o.NegatedWhy
	}
}

// escapePipes keeps a reason containing a pipe from breaking the table.
func escapePipes(s string) string { return strings.ReplaceAll(s, "|", `\|`) }

func writeNative(ctx context.Context, b *strings.Builder, root string) error {
	b.WriteString("## Native reference\n\n")
	b.WriteString("Generated from the commands' own `--help`.\n\n")

	for _, path := range nativeCommands {
		help, err := helpFor(ctx, root, path)
		if err != nil {
			return err
		}
		title := "imapsync-go"
		if len(path) > 0 {
			title += " " + strings.Join(path, " ")
		}
		fmt.Fprintf(b, "### `%s`\n\n```\n%s```\n\n", title, help)
	}
	return nil
}

// helpFor runs one command with --help and returns what it printed.
func helpFor(ctx context.Context, root string, path []string) (string, error) {
	args := append([]string{"run", "./cmd/imapsync-go"}, path...)
	args = append(args, "--help")

	cmd := exec.CommandContext(ctx, "go", args...) //nolint:gosec // an argument vector this file builds
	cmd.Dir = root

	var out, errb bytes.Buffer
	cmd.Stdout = &out
	cmd.Stderr = &errb
	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("running help for %v: %w: %s", path, err, errb.String())
	}

	text := out.String()
	if !strings.HasSuffix(text, "\n") {
		text += "\n"
	}
	return text, nil
}
