name: Lint

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          check-latest: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.13.2

  goreleaser-check:
    name: goreleaser check
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          check-latest: true
      - name: Validate .goreleaser.yaml
        uses: goreleaser/goreleaser-action@v7
        with:
          version: '~> v2'
          args: check
